# Generated by Django 5.0.3 on 2024-03-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='vehicle brand (e.g: Toyota)')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='vehicle category (e.g: SUV)')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='vehicle model (e.g: Hilux)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.brand', verbose_name='vehicle brand (reference)')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField(verbose_name='model year')),
                ('price', models.FloatField(verbose_name='price in ARS')),
                ('thumbnail', models.ImageField(upload_to='vehicle/thumbnail/', verbose_name='vehicle image (thumbnail)')),
                ('categories', models.ManyToManyField(to='vehicle.category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.model', verbose_name='vehicle model (reference)')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.TextField(verbose_name='hero section title')),
                ('hero_phrase', models.TextField(verbose_name='hero section subtitle')),
                ('hero_description', models.TextField(verbose_name='hero section paragraph')),
                ('hero_image', models.ImageField(upload_to='vehicle/hero/', verbose_name='vehicle image (main)')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='vehicle (reference)')),
            ],
            options={
                'verbose_name': 'vehicle site',
                'verbose_name_plural': 'vehicle sites',
            },
        ),
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('text', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='vehicle/sites/selling/', verbose_name='selling point image')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclesite', verbose_name='vehicle website (reference)')),
            ],
            options={
                'verbose_name': 'selling point',
                'verbose_name_plural': 'selling points',
            },
        ),
        migrations.CreateModel(
            name='FeatureDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('text', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='vehicle/sites/feature/', verbose_name='feature image')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclesite', verbose_name='vehicle website (reference)')),
            ],
            options={
                'verbose_name': 'feature description',
                'verbose_name_plural': 'feature descriptions',
            },
        ),
    ]
